### ISSUE TITLE
Grouped table section headers in the wrong font...

### ISSUE THREAD

**Issue by digitalmoksha** [infinitered/redpotion-template#18]
If you add a grouped table to the default app that's created, the section headers are in a huge font, rather than their default font, which is smaller, gray, and all caps.

The code in the default `app/stylesheets/appearance.rb` sets the font for all UILabel instances.  

```
      UILabel.appearance.tap do |o|
        o.setTextColor rmq.color.black
        o.font = rmq.font.medium
      end
```

I would recommend this to be commented out initially, not to cause confusion and allow the default behavior.

**Comment by jamonholmgren** [comment]
@digitalmoksha Sorry about the delayed response, apparently we missed this. Would you want to submit a pull request?

**Comment by digitalmoksha** [comment]
You bet, added pull request #19

**Comment by andrewhavens** [comment]
Merged!
